### ISSUE TITLE
希望能够添加一个，首页只有搜索框，没有直播、推荐、热门的模式，大致如图。

### ISSUE THREAD

**Issue by XIYOUNIAO** [cledwynl/mbga#11]
![Screenshot_2024-02-02-01-10-55-708_com mmbox xbrowser pro](https://github.com/cledwynl/mbga/assets/86189536/8ae291c7-2d82-4f59-9e6b-333e2deab7d7)

**Comment by cledwynl** [comment]
把首页中间那堆内容干掉应该问题不大，但要把搜索框弄到中间来有点难。最近事多，春节的时候再看看

**Comment by cledwynl** [comment]
有点蛋疼的，研究了好久不知道怎样把搜索框弄到中间来。换个思路，你觉得在动态或者设置页里加一个搜索页面的入口如何？
![image](https://github.com/cledwynl/mbga/assets/16000170/a32dce27-3a1e-428d-a958-14266bd2a121)
![image](https://github.com/cledwynl/mbga/assets/16000170/70d40499-d888-41d1-b407-5e00194f4bb0)

**Comment by XIYOUNIAO** [comment]
感谢大佬的回复，搜索框不弄到中间也可以，两种方案中我个人更喜欢设置页里加一个搜索页面的入口。感谢大佬的热心付出。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cledwyn ***@***.***&gt;; 
发送时间: 2024年3月30日(星期六) 中午12:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cledwynl/mbga] 希望能够添加一个，首页只有搜索框，没有直播、推荐、热门的模式，大致如图。 (Issue #11)














 
有点蛋疼的，研究了好久不知道怎样把搜索框弄到中间来。换个思路，你觉得在动态或者设置页里加一个搜索页面的入口如何？
 image.png (view on web)
 image.png (view on web)
