### ISSUE TITLE
底部Tab增加隱藏節目選項

### ISSUE THREAD

**Issue by NeKoOuO** [cledwynl/mbga#13]
![IMG_20240227_193204.jpg](https://github.com/cledwynl/mbga/assets/111511925/27ce3a33-5ae1-46ec-9361-c3096073527a)

如圖

**Comment by cledwynl** [comment]
没太明白，附图说明一下？

**Comment by cledwynl** [comment]
不知道是app版本不一样还是账号区域不一样，我这没这个tab。不过我在代码里挖出来了一些可能是tab的东西，我都加上去。试试这个功能包看看pegasus_channel是你这的节目不？
[top.trangle.mbga-v4(1.0.2_feature-more-tab-control).zip](https://github.com/cledwynl/mbga/files/14471825/top.trangle.mbga-v4.1.0.2_feature-more-tab-control.zip)

**Comment by NeKoOuO** [comment]
好像不是....我開了還是有
![Screenshot_2024-03-03-22-58-34-357_com.bilibili.app.in.jpg](https://github.com/cledwynl/mbga/assets/111511925/1a86aa76-2099-46cf-bab9-edfe5ef1bc33)

![Screenshot_2024-03-03-22-58-26-249_top.trangle.mbga.jpg](https://github.com/cledwynl/mbga/assets/111511925/dea7804f-5837-4f1d-bb14-9ad6169c3638)

**Comment by cledwynl** [comment]
你的B站是3.18.2版吗，不是的话发我一份看看吧

**Comment by NeKoOuO** [comment]
> 你的B站是3.18.2版吗，不是的话发我一份看看吧

是的

**Comment by cledwynl** [comment]
底部tab似乎是通过网络获取的，你装一下这个版本，这个版本会把底部tab的uri打印到日志里，就能找出需要屏蔽的uri了
[top.trangle.mbga-v4(1.0.2_feature-more-tab-control).zip](https://github.com/cledwynl/mbga/files/14572290/top.trangle.mbga-v4.1.0.2_feature-more-tab-control.zip)

**Comment by cledwynl** [comment]
有通用的解法了，在底栏的hook里把所有tab都传给设置界面，设置界面展示所有tab的开关。但依赖的框架似乎对我们这样的模块形式支持不是很好 https://github.com/HighCapable/YukiHookAPI/issues/68 ，还得继续打磨好了再发布。
