### ISSUE TITLE
禁止短链建议

### ISSUE THREAD

**Issue by BakaJzon** [cledwynl/mbga#14]
~~非常好功能，使我的链接延长。~~

众所周知，b23.tv除了接收带追踪的链接外，还可以直接跟av/bv号跳转。
这样的话可以缩短分享链接，同时对使用体验影响不大。

如：
<http://b23.tv/av170001>
<https://b23.tv/BV1GJ411x7h7>

**Comment by cledwynl** [comment]
计划明天发布
