### ISSUE TITLE
能否添加在小窗/分屏模式下，允许视频全屏播放

### ISSUE THREAD

**Issue by chs72** [cledwynl/mbga#26]
类名tv.danmaku.bili.videopage.player.widget.control.PlayerFullscreenWidget，方法名V1，HOOK返回值为false。不会java，求助大佬。

**Comment by cledwynl** [comment]
比如在MIUI下把B站弄成小窗，然后点击B站播放器的全屏按钮，会提示“分屏模式下暂不支持全屏播放”对吗

**Comment by chs72** [comment]
> 比如在MIUI下把B站弄成小窗，然后点击B站播放器的全屏按钮，会提示“分屏模式下暂不支持全屏播放”对吗

是的

**Comment by cledwynl** [comment]
@chs72 3.19.0上G了，有兴趣来找找注入点吗
