### ISSUE TITLE
主页进入搜索页面后返回主界面会刷新主页，

### ISSUE THREAD

**Issue by YanagiAsahi** [cledwynl/mbga#27]
想不到吧，这里也调用了刷新的接口，草

**Comment by cledwynl** [comment]
首页有两种刷新法，一种是下拉刷新，会在列表顶部加载新内容，第二种是点击底部tab刷新，会把整个裂变都干掉重新加载。我想要不直接把第二种拦截下来换成第一种，这样就算刷新了也还能看到原来的内容

**Comment by YanagiAsahi** [comment]
这个我也不太懂，我只能作为一个用户感觉这刷新有点，额，嘛硬推流，主要还是之前的被刷走了，有时候看到标题有点兴趣进去看看，结果被刷走了，

Cledwyn Lew ***@***.***> 于 2024年4月4日周四 07:58写道：
