### ISSUE TITLE
bilibili_play_3.19.0今日更新

### ISSUE THREAD

**Issue by Stop-586** [cledwynl/mbga#34]
MBGA在bilibli_play_3.19.0上，已全部失效

**Comment by Cathgao** [comment]
我升级了最新国际版之后也是全部失效了，客户端设置里面也看不到模块的设置。
然后我重装了3.61的客户端和模块，第一次打开客户端能弹出来模块设置，但还是全部不生效，客户端设置里也看不到模块的设置。这个是什么问题？

**Comment by Stop-586** [comment]
> 我升级了最新国际版之后也是全部失效了，客户端设置里面也看不到模块的设置。
> 然后我重装了3.61的客户端和模块，第一次打开客户端能弹出来模块设置，但还是全部不生效，客户端设置里也看不到模块的设置。这个是什么问题？
> 
> -----------------------
> 测试3.18.2国际版是可以正常工作

3.18.1/3.18.2模块工作正常，至于3.19我们都在等作者更新，可能作者还没做适配，耐心等待

**Comment by cledwynl** [comment]
代码变化好像挺大的，我得花点时间看看怎样兼容不同版本

**Comment by SolitaryEgo** [comment]
> 代码变化好像挺大的，我得花点时间看看怎样兼容不同版本

加油，催更

**Comment by cledwynl** [comment]
[top.trangle.mbga-v9(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/cledwynl/mbga/files/15251403/top.trangle.mbga-v9.1.1.0_feature-bili-3.19.0.apk.zip)

等不及的话可以先试试这个版本，有一部分功能好了。下载后把.zip后缀删掉安装

**Comment by Stop-586** [comment]
> [top.trangle.mbga-v9(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/cledwynl/mbga/files/15251403/top.trangle.mbga-v9.1.1.0_feature-bili-3.19.0.apk.zip)
> 
> 等不及的话可以先试试这个版本，有一部分功能好了。下载后把.zip后缀删掉安装

谢谢开发者，不急，我们可以先用着3.18.2，等待你的适配3.19，辛苦了

**Comment by cledwynl** [comment]
[top.trangle.mbga-v10(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/cledwynl/mbga/files/15286040/top.trangle.mbga-v10.1.1.0_feature-bili-3.19.0.apk.zip)

来了来了，除了隐藏首页底部tab的功能还没好，其他应该都好了，你们试试看。

底部tab等下周有空再弄了，然后还得优化一下兼容性，还没那么快发正式版

**Comment by cledwynl** [comment]
[top.trangle.mbga-v11(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/cledwynl/mbga/files/15447622/top.trangle.mbga-v11.1.1.0_feature-bili-3.19.0.apk.zip)

好久不见，来一版更新

已知：首页底部tab隐藏没弄好，视频标题左边标签没干掉。

**Comment by Stop-586** [comment]
收到，感谢，作者辛苦了！



---原始邮件---
发件人: "Cledwyn ***@***.***&gt;
发送时间: 2024年5月26日(周日) 晚上9:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cledwynl/mbga] bilibili_play_3.19.0今日更新 (Issue #34)




 
top.trangle.mbga-v11(1.1.0_feature-bili-3.19.0).apk.zip
 
好久不见，来一版更新
 
已知：首页底部tab隐藏没弄好，视频标题左边标签没干掉。

**Comment by SolitaryEgo** [comment]
> [top.trangle.mbga-v11(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/cledwynl/mbga/files/15447622/top.trangle.mbga-v11.1.1.0_feature-bili-3.19.0.apk.zip)
> 
> 好久不见，来一版更新
> 
> 已知：首页底部tab隐藏没弄好，视频标题左边标签没干掉。

b站3.19版本能看到ip地址，但是得进视频，然后进主页再进视频才能在头像旁看到，能考虑做一个直接显示ip的功能？

**Comment by Stop-586** [comment]
目前 模块top.trangle.mbga-v11(1.1.0 feature-bili- 3.19.0)，在bilibili3.19.1最新版上是生效状态，特此反馈

**Comment by BTmanMk2** [comment]
3.19.1竖屏视频全屏时会切回竖屏播放器

**Comment by cledwynl** [comment]
[top.trangle.mbga-v12(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/user-attachments/files/15889728/top.trangle.mbga-v12.1.1.0_feature-bili-3.19.0.apk.zip)


新版来咯～这个版本把视频标题左边的标签干掉了，还干掉了播放器竖屏全屏按钮
现在只剩首页底部tab隐藏没弄好了

应该这周末就能发个正式版

**Comment by cledwynl** [comment]
> b站3.19版本能看到ip地址，但是得进视频，然后进主页再进视频才能在头像旁看到，能考虑做一个直接显示ip的功能？

@SolitaryEgo 单独提一个issue跟踪吧，不过以我的能力不一定能实现XD

**Comment by cledwynl** [comment]
大功告成，PR合进去了，明天或者后端发正式版

**Comment by qa9633** [comment]
> [top.trangle.mbga-v12(1.1.0_feature-bili-3.19.0).apk.zip](https://github.com/user-attachments/files/15889728/top.trangle.mbga-v12.1.1.0_feature-bili-3.19.0.apk.zip)
> 
> 新版来咯～这个版本把视频标题左边的标签干掉了，还干掉了播放器竖屏全屏按钮 现在只剩首页底部tab隐藏没弄好了
> 
> 应该这周末就能发个正式版

大佬，新版在哪里下载，我刚刚用这个平台不太清楚怎么玩
