### ISSUE TITLE
禁止快速回复功能误将点击笔记弹出详情干掉了

### ISSUE THREAD

**Issue by cledwynl** [cledwynl/mbga#36]
特别是没有评论的笔记，完全没法点开查看

影响的B站版本: 3.18.2

**Comment by ghjjvbjj** [comment]
作者还是没有适配3.19.0吗？

**Comment by cledwynl** [comment]
> 作者还是没有适配3.19.0吗？

3.19.0进展在这 #34

**Comment by cledwynl** [comment]
手上设备全升级到3.19.x了，不打算修了。
