### ISSUE TITLE
更纯净的分享链接在非视频的分享对象时有bug

### ISSUE THREAD

**Issue by cledwynl** [cledwynl/mbga#39]
比如分享动态，会复制出 `https://b32.tv/av${动态ID}` 这样的错误链接来

**Comment by UVJkiNTQ** [comment]
类似的，分享直播间会跳转到不相干的视频。

**Comment by cledwynl** [comment]
新增了两种支持的分享对象：动态、直播。

如果分享对象不是支持的，则会回退至B站原始的短链生成逻辑
