### ISSUE TITLE
希望能把首页干掉，只看动态

### ISSUE THREAD

**Issue by tomthenpc** [cledwynl/mbga#4]
不知道能不能把首页干掉，只看自己订阅的频道。

**Comment by cledwynl** [comment]
我试试看，之前看起来动底部tab有点难度

**Comment by cledwynl** [comment]
但是首页被干掉以后搜索也没了，体验可能不太好

**Comment by cledwynl** [comment]
相关代码片段：

* `tv.danmaku.bili.ui.main2.MainFragment$a.a` 这个函数会生成tab列表，具体怎么生成的待研究
