### ISSUE TITLE
请问怎么使用啊

### ISSUE THREAD

**Issue by LMIRAK** [cledwynl/mbga#43]
我反复安装多个版本后都没有效果

**Comment by cledwynl** [comment]
你用的是LSPosed框架吗，要在LSPosed里启用MBGA然后选中B站国际版之后重启B站

**Comment by LMIRAK** [comment]
我以为安装后即可使用

**Comment by LMIRAK** [comment]
> 你用的是LSPosed框架吗，要在LSPosed里启用MBGA然后选中B站国际版之后重启B站

我用的是LSPatch
