### ISSUE TITLE
有内置模块版本的APP包么？

### ISSUE THREAD

**Issue by 932749734** [cledwynl/mbga#50]
如题。3.19.2

**Comment by cledwynl** [comment]
还没有，需要找出签名校验的地方，简单的反编译再回编译运行起来会闪退。等签名校验绕过去以后就能自己用 LSPatch 打包了 #44 。不过我应该不会提供内置模块的APP包，担心法律风险。

这个 issue 和支持 LSPatch 是同一个问题，我就关闭了

**Comment by zjns** [comment]
lspatch本身是有选项支持过签的
