### ISSUE TITLE
请求添加 隐藏评论区顶部“大家都在搜” 功能

### ISSUE THREAD

**Issue by SciAres2020** [cledwynl/mbga#52]
最近几天 bilibili 部分视频评论区顶部出现了“大家都在搜：xxx”,非常烦人。
![Uploading S40929-17445403_com.bilibili.app.in.png…]()

**Comment by cledwynl** [comment]
你的图没上传成功。有稳定复现的视频链接吗

**Comment by SciAres2020** [comment]
> 你的图没上传成功。 有稳定复现的视频链接吗

好像不能稳定复现   AV113151500 我的其中一个帐号每次都有，但另一个账号没有。
![S40929-17445403_com bilibili app in](https://github.com/user-attachments/assets/0012c229-1470-4658-bd65-ec4f153b3684)

**Comment by cledwynl** [comment]
v1.2.0发布了，在选项里启用“记录MainListReply”，以后再出现“大家都在搜”的话发一下日志，应该就有思路干掉它了

**Comment by SciAres2020** [comment]
请问日志文件在哪？没找到

**Comment by cledwynl** [comment]
打开lsposed，底部tab第4个就是日志

**Comment by SciAres2020** [comment]
不确定是不是这个
[LSPosed_2024-10-02T18_05_49.172679.zip](https://github.com/user-attachments/files/17227886/LSPosed_2024-10-02T18_05_49.172679.zip)

**Comment by cledwynl** [comment]
没错是这样的日志，但是这个日志里没有MainListReply相关内容，请确认一下开发者选项里勾选对了“记录MainListReply”，然后遇到“大家都在搜”之后再导出一次日志

**Comment by SciAres2020** [comment]
[LSPosed_2024-10-03T16_53_19.306202.zip](https://github.com/user-attachments/files/17241775/LSPosed_2024-10-03T16_53_19.306202.zip)

**Comment by cledwynl** [comment]
> [LSPosed_2024-10-03T16_53_19.306202.zip](https://github.com/user-attachments/files/17241775/LSPosed_2024-10-03T16_53_19.306202.zip)

好像没上传成功，点开404了

**Comment by cledwynl** [comment]
![image](https://github.com/user-attachments/assets/609c325d-2217-4f90-a466-aff33a2891a6)

我这出现了这个东西，看起来是同一个组件，知道怎样处理了

**Comment by SciAres2020** [comment]
[LSPosed_2024-10-05T18_38_31.179932.zip](https://github.com/user-attachments/files/17265814/LSPosed_2024-10-05T18_38_31.179932.zip)
补一下日志

**Comment by cledwynl** [comment]
可以试试 1.3.0-rc1，过几天没发现问题的话就可以发布了。issue 先 close，如果发现问题请 reopen

https://github.com/cledwynl/mbga/releases/tag/v1.3.0-rc1
