### ISSUE TITLE
无法评论

### ISSUE THREAD

**Issue by UVJkiNTQ** [cledwynl/mbga#58]
版本1.2.0

Bili app版本：
intl：3.19.2
视频及动态均无法评论（点不开）

弹幕部分正常（包括直播间）

**Comment by seraph758** [comment]
![Screenshot_2024-10-14-18-08-56-55_18fe6f119af5ae2c728d929083699df1](https://github.com/user-attachments/assets/63dbd472-e499-4cc5-a00c-b6de4fc0ffc1)
今天发现评论区直接点不能回复，但是点这里还是让回复的
