### ISSUE TITLE
请求可以关闭视频横屏状态下的亮度/音量调节

### ISSUE THREAD

**Issue by boxendo** [cledwynl/mbga#73]
![Screenshot_2024-11-10-00-49-24-557_com bilibili app in-edit](https://github.com/user-attachments/assets/b886909c-80e7-4533-a4bd-deeb77c1c54b)
![Screenshot_2024-11-10-00-50-18-098_com bilibili app in-edit](https://github.com/user-attachments/assets/3b6b839a-1d0f-41c9-a1d0-4ccd758207cc)
大概就是这两边的滑动调节
主要是平常使用真的很容易误触，特别是晚上在低亮度下看视频，不小心碰到亮度就会亮瞎眼（而且必须要退出视频再进才能恢复原来的亮度）
可以的话，希望能加一个开关控制这两个滑条，感谢大佬！

还有一个，在滑屏幕调节视频进度的时候（不是滑进度条），有时候会出现“松开手指 取消跳转”，然后就导致滑了好几次屏幕却只跳了一点点进度，同样很容易误触，如果可以也希望大佬能加一个关闭这个功能的开关，谢谢大佬付出！

**Comment by cledwynl** [comment]
看起来视频播放器右边的锁定按钮能满足你的需要？

**Comment by cledwynl** [comment]
看起来挺难实现的，播放器的代码是js写的，用xposed没法直接注入。如果把native向js传递的触摸事件干掉又会误伤左右调整进度
