### ISSUE TITLE
与哔哩漫游同时启用 下载视频功能失效 未勾选任何功能也一样无法下载

### ISSUE THREAD

**Issue by S-ZHIWEI** [cledwynl/mbga#85]
bilibili是当前最新版3.20.0

**Comment by S-ZHIWEI** [comment]
> [LSPosed_2024-12-31T13_26_47.088570.zip](https://github.com/user-attachments/files/18279464/LSPosed_2024-12-31T13_26_47.088570.zip) [log.txt](https://github.com/user-attachments/files/18279465/log.txt) ![Screenshot_2024-12-31-13-26-34-298_com bilibili app in](https://private-user-images.githubusercontent.com/62824399/399413824-7d1b0218-6ab6-4fc8-9f4b-72245b6b8094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MjQyMTcsIm5iZiI6MTczNTYyMzkxNywicGF0aCI6Ii82MjgyNDM5OS8zOTk0MTM4MjQtN2QxYjAyMTgtNmFiNi00ZmM4LTlmNGItNzIyNDViNmI4MDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA1NDUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZDg4YTI5ZWIyOWRlNWUxNjgxNGYxZjI5MjNhOTdiMTZiNTAyMmUwNWI4NzkyZTUxMGY3MTUyM2YxZDAyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ApLYnkaRUzdyxow3ktUad9viD2iCqoRyYQbd0Ut9r4M) bilibili是当前最新版3.20.0

**Comment by S-ZHIWEI** [comment]
再次排查发现是哔哩漫游未适配 bilibili降级至3.19.2可正常缓存视频

**Comment by S-ZHIWEI** [comment]
是哔哩漫游CI未适配最新版bilibili 打扰了

**Comment by cledwynl** [comment]
我超，B站又更新了吗，那又得测兼容性了
